[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10.10"
ic-cdk = "0.18.3"
ic-stable-structures = "0.6.7"
rand = "0.8"
rand_chacha = "0.3"
getrandom = { version = "0.2", features = ["custom"] }

